---Atributos---

<<<<<<< HEAD
/* ProductDescription */
ALTER TABLE ProductDescription ADD CONSTRAINT CK_DESCRIPTIONISNOTNULL CHECK (Description IS NOT NULL);

/* ProductModel */
ALTER TABLE ProductModel ADD CONSTRAINT CK_NAMEMODELNOTNULL CHECK ( Name IS NOT NULL );

/* Product */
=======
--ProductDescription--
ALTER TABLE ProductDescription ADD CONSTRAINT CK_DESCRIPTIONISNOTNULL CHECK (Description IS NOT NULL);

--ProductCategory--
ALTER TABLE ProductCategory ADD CONSTRAINT CK_NAMENOTNULL CHECK (Name IS NOT NULL);

--ProductModel--
ALTER TABLE ProductModel ADD CONSTRAINT CK_NAMEMODELNOTNULL CHECK ( Name IS NOT NULL );

--Product--
>>>>>>> 59ef20ab8a4c63f9dd2cd9e2e5fdfa657aaa5983
ALTER TABLE Product ADD CONSTRAINT CK_NAMEPRODUCT CHECK (Name IS NOT NULL );
ALTER TABLE Product ADD CONSTRAINT CK_PRODUCTNUMBER CHECK (ProductNumber IS NOT NULL );
ALTER TABLE Product ADD CONSTRAINT CK_STANDARDCOST CHECK (StandardCost IS NOT NULL );
ALTER TABLE Product ADD CONSTRAINT CK_LISTPRICE CHECK (ListPrice IS NOT NULL );
ALTER TABLE Product ADD CONSTRAINT CK_SELLSTARTDATE CHECK ( SellStartDate IS NOT NULL );

<<<<<<< HEAD
/* Customer */
=======
--Customer--
>>>>>>> 59ef20ab8a4c63f9dd2cd9e2e5fdfa657aaa5983
ALTER TABLE Customer ADD CONSTRAINT CK_NAMESTYLEISNOTNULL CHECK (NameStyle IS NOT NULL);
ALTER TABLE Customer ADD CONSTRAINT CK_FIRSTNAMEISNOTNULL CHECK (FirstName IS NOT NULL);
ALTER TABLE Customer ADD CONSTRAINT CK_LASTNAMEISNOTNULL CHECK (LastName IS NOT NULL);
ALTER TABLE Customer ADD CONSTRAINT CK_PASSWORDHASHISNOTNULL CHECK (PasswordHash IS NOT NULL);
ALTER TABLE Customer ADD CONSTRAINT CK_PASSWORDSALTISNOTNULL CHECK (PasswordSalt IS NOT NULL);

<<<<<<< HEAD
/* CustomerAddress */
ALTER TABLE CustomerAddress ADD CONSTRAINT CK_ADDRESSIDISNOTNULL CHECK (AddressID IS NOT NULL);


/* SalesOrderHeader */
=======
--CustomerAddress--
ALTER TABLE CustomerAddress ADD CONSTRAINT CK_ADDRESSIDISNOTNULL CHECK (AddressID IS NOT NULL);

--SalesOrderHeader--
>>>>>>> 59ef20ab8a4c63f9dd2cd9e2e5fdfa657aaa5983
ALTER TABLE SalesOrderHeader ADD CONSTRAINT CK_REVISIONNUMBER CHECK (RevisionNumber IS NOT NULL);
ALTER TABLE SalesOrderHeader ADD CONSTRAINT CK_ORDERDATE CHECK (OrderDate IS NOT NULL);
ALTER TABLE SalesOrderHeader ADD CONSTRAINT CK_DUEDATE CHECK (DueDate IS NOT NULL);
ALTER TABLE SalesOrderHeader ADD CONSTRAINT CK_SHIPDATE CHECK (ShipDate IS NOT NULL);
ALTER TABLE SalesOrderHeader ADD CONSTRAINT CK_SATATUS CHECK (Status IS NOT NULL);
ALTER TABLE SalesOrderHeader ADD CONSTRAINT CK_ONLINEORDERFLAG CHECK (OnlineOrderFlag IS NOT NULL);
ALTER TABLE SalesOrderHeader ADD CONSTRAINT CK_CUSTOMERID CHECK (CustomerID IS NOT NULL);
ALTER TABLE SalesOrderHeader ADD CONSTRAINT CK_SHIPMETHOD CHECK (ShipMethod IS NOT NULL);
ALTER TABLE SalesOrderHeader ADD CONSTRAINT CK_SUBTOTAL CHECK (SubTotal IS NOT NULL);
ALTER TABLE SalesOrderHeader ADD CONSTRAINT CK_TAXAMT CHECK (TaxAmt IS NOT NULL);
ALTER TABLE SalesOrderHeader ADD CONSTRAINT CK_FREIGHT CHECK (Freight IS NOT NULL);

<<<<<<< HEAD
/*  SalesOrderDetail */
=======
--SalesOrderDetail--
>>>>>>> 59ef20ab8a4c63f9dd2cd9e2e5fdfa657aaa5983
ALTER TABLE SalesOrderDetail ADD CONSTRAINT CK_SALESORDERID CHECK (SalesOrderID IS NOT NULL );
ALTER TABLE SalesOrderDetail ADD CONSTRAINT CK_ORDERQTY CHECK (OrderQty IS NOT NULL );
ALTER TABLE SalesOrderDetail ADD CONSTRAINT CK_PRODUCTID CHECK (ProductID IS NOT NULL );
ALTER TABLE SalesOrderDetail ADD CONSTRAINT CK_UNITPRICEISNOTNULL CHECK (UnitPrice IS NOT NULL );
ALTER TABLE SalesOrderDetail ADD CONSTRAINT CK_UNITPRICEDISCOUNT CHECK (UnitPriceDiscount IS NOT NULL);
